### ISSUE TITLE
Cannot connect to Bluemix CF

### ISSUE THREAD

**Issue by lucaverderame** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#141]
Dear developer,

I'm running a Spring Cloud DataFlow v. 1.0.0.M3 on Bluemix PaaS. Those are the environment variables set:

```
{
  "SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN" : "eu-gb.mybluemix.net",
  "SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_ORG" : "MY ORGANIZATION",
  "SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_PASSWORD" : "MY_PASS",
  "SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SERVICES" : "redis01,rabbit",
  "SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION" : "false",
  "SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SPACE" : "MY SPACE",
  "SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_URL" : "https://api.eu-gb.bluemix.net",
  "SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_USERNAME" : "MY USER"
}
```

Unfortunateley, we I try to deploy `stream create ticksample4 --definition "time | log" --deploy` I obtain the following error:

```
ERROR 29 --- [io-61127-exec-7] o.s.c.d.s.c.CloudFoundryAppDeployer      : Error creating app dataflow-uncloistered-ideomotion-ticksample4-log
    org.springframework.security.oauth2.client.resource.OAuth2AccessDeniedException: Error requesting access token.
at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport.retrieveToken(OAuth2AccessTokenSupport.java:145) ~[spring-security-oauth2-2.0.9.RELEASE.jar!/:na]
at org.springframework.security.oauth2.client.token.grant.password.ResourceOwnerPasswordAccessTokenProvider.obtainAccessToken(ResourceOwnerPasswordAccessTokenProvider.java:47) ~[spring-security-oauth2-2.0.9.RELEASE.jar!/:na]
at org.springframework.security.oauth2.client.OAuth2RestTemplate.acquireAccessToken(OAuth2RestTemplate.java:221) ~[spring-security-oauth2-2.0.9.RELEASE.jar!/:na]
at org.springframework.security.oauth2.client.OAuth2RestTemplate.getAccessToken(OAuth2RestTemplate.java:173) ~[spring-security-oauth2-2.0.9.RELEASE.jar!/:na]
at org.springframework.security.oauth2.client.OAuth2RestTemplate.createRequest(OAuth2RestTemplate.java:105) ~[spring-security-oauth2-2.0.9.RELEASE.jar!/:na]
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:592) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128) ~[spring-security-oauth2-2.0.9.RELEASE.jar!/:na]
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:280) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.cloudfoundry.spring.util.AbstractSpringOperations.lambda$get$3(AbstractSpringOperations.java:85) ~[cloudfoundry-client-spring-2.0.0.M4.jar!/:2.0.0.M4]
at org.cloudfoundry.spring.util.AbstractSpringOperations.lambda$null$1(AbstractSpringOperations.java:66) ~[cloudfoundry-client-spring-2.0.0.M4.jar!/:2.0.0.M4]
at reactor.core.publisher.FluxYieldingEmitter$YieldingSignalEmitter.request(FluxYieldingEmitter.java:75) ~[reactor-core-2.5.0.M3.jar!/:na]
at reactor.core.util.DeferredSubscription.set(DeferredSubscription.java:71) ~[reactor-core-2.5.0.M3.jar!/:na]
at reactor.core.publisher.FluxSubscribeOn$SubscribeOnPipeline.onSubscribe(FluxSubscribeOn.java:129) ~[reactor-core-2.5.0.M3.jar!/:na]
at reactor.core.subscriber.SignalEmitter.start(SignalEmitter.java:170) ~[reactor-core-2.5.0.M3.jar!/:na]
at reactor.core.publisher.FluxYieldingEmitter.subscribe(FluxYieldingEmitter.java:43) ~[reactor-core-2.5.0.M3.jar!/:na]
at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:153) ~[reactor-core-2.5.0.M3.jar!/:na]
at reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:170) ~[reactor-core-2.5.0.M3.jar!/:na]
at reactor.core.publisher.FluxSubscribeOn$SourceSubscribeTask.run(FluxSubscribeOn.java:363) ~[reactor-core-2.5.0.M3.jar!/:na]
at reactor.core.publisher.Computations$ProcessorWorker.onNext(Computations.java:919) ~[reactor-core-2.5.0.M3.jar!/:na]
at reactor.core.publisher.Computations$ProcessorWorker.onNext(Computations.java:883) ~[reactor-core-2.5.0.M3.jar!/:na]
at reactor.core.publisher.WorkQueueProcessor$QueueSubscriberLoop.run(WorkQueueProcessor.java:842) ~[reactor-core-2.5.0.M3.jar!/:na]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_91]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_91]
at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_91]
     OUT Caused by: org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport$AccessTokenErrorHandler.handleError(OAuth2AccessTokenSupport.java:244) ~[spring-security-oauth2-2.0.9.RELEASE.jar!/:na]
at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:565) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport.retrieveToken(OAuth2AccessTokenSupport.java:137) ~[spring-security-oauth2-2.0.9.RELEASE.jar!/:na]
... 24 common frames
```

It seems that is not able to authenticate to Bluemix to deploy the stream. I successfully deploy the stram only on version 1.0.0.M1, since it expose:

```
"SECURITY_OAUTH2_CLIENT_ACCESS_TOKEN_URI" : "https://login.eu-gb.bluemix.net/UAALoginServerWAR/oauth/token",
  "SECURITY_OAUTH2_CLIENT_PASSWORD" : "MY PASS",
  "SECURITY_OAUTH2_CLIENT_USERNAME" : "MY USER",
  "SECURITY_OAUTH2_CLIENT_USER_AUTHORIZATION_URI" : "https://login.eu-gb.bluemix.net/UAALoginServerWAR/oauth/authorize" 
```

But I'm not able to add those variables also in version 1.0.0.M3. Did I miss something? Is my approach faulty?

P.S. I tested the 1.0.0.M3 version on Pivotal Cloud Foundry and it works like a charm.

Many thanks for any help you may provide

Luca

**Comment by markpollack** [comment]
These configuration properties/env-vars are documented in http://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/1.1.0.BUILD-SNAPSHOT/reference/htmlsingle/#configuration-security-oauth2

e.g.

```
security:
  basic:
    enabled: true                                                     
    realm: Spring Cloud Data Flow                                     
  oauth2:                                                             
    client:
      client-id: myclient
      client-secret: mysecret
      access-token-uri: http://127.0.0.1:9999/oauth/token
      user-authorization-uri: http://127.0.0.1:9999/oauth/authorize
    resource:
      user-info-uri: http://127.0.0.1:9999/me
```

which is what you are looking for.  Please reopen the issue if this doesn't work for you.  Thanks for reporting this and sorry for the long delay in responding.
