### ISSUE TITLE
Tasks aren't connecting to the mysql service automatically

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#186]
As a user, I'm running tasks (_with the [right driver](https://github.com/spring-cloud/spring-cloud-task-app-starters/blob/master/spring-cloud-starter-task-timestamp/pom.xml#L43)_) on CF; however, I'm unable to get the task application to bootstrap successfully. This is happening on both pcfdev and pws environments. 

Following env-var's are set:
```
    SPRING_APPLICATION_NAME: sabby-dataflow-server
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_URL: https://api.local.pcfdev.io
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_ORG: pcfdev-org
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SPACE: pcfdev-space
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN: local.pcfdev.io
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_SERVICES: redis,rabbit,mysql
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_SERVICES: mysql
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_MEMORY: 512
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_DISK: 512
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_USERNAME: admin
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_PASSWORD: admin
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION: true
    MAVEN_REMOTE_REPOSITORIES_REPO1_URL: https://repo.spring.io/libs-snapshot
    SPRING_CLOUD_DATAFLOW_FEATURES_EXPERIMENTAL_TASKSENABLED: true
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_ENABLE_RANDOM_APP_NAME_PREFIX: false
```

**task:**
```
dataflow:>task create foo --definition "timestamp"
Created new task 'foo'

dataflow:>task launch foo
Launched task 'foo'
```

**error:**
```
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR Caused by: org.springframework.jdbc.support.MetaDataAccessException: Could not get Connection for extracting meta data; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.ConnectException: Connection refused: localhost:19092" [90067-191]
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:302)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:329)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.springframework.batch.support.DatabaseType.fromMetaData(DatabaseType.java:97)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.springframework.cloud.task.repository.support.TaskExecutionDaoFactoryBean.buildTaskExecutionDao(TaskExecutionDaoFactoryBean.java:102)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	... 35 more
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.ConnectException: Connection refused: localhost:19092" [90067-191]
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:289)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	... 38 more
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR Caused by: org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.ConnectException: Connection refused: localhost:19092" [90067-191]
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.h2.message.DbException.get(DbException.java:168)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:452)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:329)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.h2.Driver.connect(Driver.java:72)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:307)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:200)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:708)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:642)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:464)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:141)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:115)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:102)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:126)
2016-09-27T12:55:57.80-0700 [APP/TASK/foo000/0]ERR 	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
```

**Comment by sabbyanandan** [comment]
Turns out, the default timeout setting was the root-cause for this error. When the async operation to launch the task times out, the application is at an inconsistent stage in the lifecycle and upon re-launch, the application continues from where it stopped and the boot configuration kicks in with a complete new datasource instance.

I confirmed the persistence of task-executions in both pcfdev/pws:

```
dataflow:>dataflow config server http://sabby-ci-dataflow-server.local.pcfdev.io
Successfully targeted http://sabby-ci-dataflow-server.local.pcfdev.io
dataflow:>task create foo --definition "timestamp"
Created new task 'foo'
dataflow:>task launch foo
Launched task 'foo'
dataflow:>task execution list
╔═════════╤══╤════════════════════════════╤════════════════════════════╤═════════╗
║Task Name│ID│         Start Time         │          End Time          │Exit Code║
╠═════════╪══╪════════════════════════════╪════════════════════════════╪═════════╣
║foo      │1 │Tue Oct 04 07:05:24 PDT 2016│Tue Oct 04 07:05:24 PDT 2016│0        ║
╚═════════╧══╧════════════════════════════╧════════════════════════════╧═════════╝
```

We will be documenting `SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_TASK_TIMEOUT` property via: #189
