### ISSUE TITLE
Querying status on a non-existing task application fails with NPE

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#242]
As a user, I deleted a task via CF CLI and then upon querying for its status in SCDF fails with NPE. 

**task:**
```
dataflow:>task create --name foo --definition "timestamp"
dataflow:>task launch foo
```

**delete task via cf cli:** [_cf version 6.22.2+a95e24c-2016-10-27_]
```
cf delete -r -f foo
```

**query for status:**
```
dataflow:>task list
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: null(null): null
```

**error:**
```
2016-12-27T14:26:47.46-0800 [APP/PROC/WEB/0]OUT 2016-12-27 22:26:47.460  INFO 20 --- [ctor-http-nio-3] s.c.CloudFoundry2630AndLaterTaskLauncher : Task org.springframework.cloud.deployer.spi.core.AppDeploymentRequest@1fb1f2a2 launch successful
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 2016-12-27 22:28:21.034 ERROR 20 --- [ctor-http-nio-1] c.d.s.c.AbstractCloudFoundryTaskLauncher : Task 044d212f-7830-4132-8710-3bf59738567f status failed
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:124) ~[reactor-core-3.0.3.RELEASE.jar!/:na]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.onNext(FluxUsing.java:312) ~[reactor-core-3.0.3.RELEASE.jar!/:na]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:380) ~[reactor-core-3.0.3.RELEASE.jar!/:na]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:942) ~[reactor-core-3.0.3.RELEASE.jar!/:na]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at reactor.ipc.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:427) ~[reactor-netty-0.6.0.BUILD-SNAPSHOT.jar!/:na]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at reactor.ipc.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113) ~[reactor-netty-0.6.0.BUILD-SNAPSHOT.jar!/:na]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1069) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT org.cloudfoundry.client.v2.CloudFoundryException: null(null): null
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at org.cloudfoundry.reactor.client.ErrorPayloadMapper.lambda$null$0(ErrorPayloadMapper.java:52) ~[cloudfoundry-client-reactor-2.1.0.BUILD-SNAPSHOT.jar!/:2.1.0.BUILD-SNAPSHOT]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at reactor.core.publisher.MonoThenMap$MonoThenApplyMain.onNext(MonoThenMap.java:98) ~[reactor-core-3.0.3.RELEASE.jar!/:na]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120) ~[reactor-core-3.0.3.RELEASE.jar!/:na]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:112) ~[reactor-core-3.0.3.RELEASE.jar!/:na]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at reactor.core.publisher.MonoReduceSeed$ReduceSubscriber.onComplete(MonoReduceSeed.java:146) ~[reactor-core-3.0.3.RELEASE.jar!/:na]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142) ~[reactor-core-3.0.3.RELEASE.jar!/:na]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at reactor.ipc.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:315) ~[reactor-netty-0.6.0.BUILD-SNAPSHOT.jar!/:na]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at reactor.ipc.netty.channel.ChannelOperations.onHandlerTerminate(ChannelOperations.java:499) ~[reactor-netty-0.6.0.BUILD-SNAPSHOT.jar!/:na]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at reactor.ipc.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:479) ~[reactor-netty-0.6.0.BUILD-SNAPSHOT.jar!/:na]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) ~[netty-all-4.1.6.Final.jar!/:4.1.6.Final]
2016-12-27T14:28:21.04-0800 [APP/PROC/WEB/0]OUT 	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
2016-12-27T14:28:21.05-0800 [APP/PROC/WEB/0]OUT 2016-12-27 22:28:21.053 ERROR 20 --- [nio-8080-exec-1] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request
2016-12-27T14:28:21.05-0800 [APP/PROC/WEB/0]OUT org.cloudfoundry.client.v2.CloudFoundryException: null(null): null
```

**Comment by cppwfs** [comment]
Just wondering if the real solution is to remove the task status from the
list.
i.e. https://github.com/spring-cloud/spring-cloud-dataflow/issues/1051

**Comment by ericbottard** [comment]
I agree that column does not make much sense. Definitely not if the query is not deterministic.

**Comment by sabbyanandan** [comment]
The core issue is at CFJC via https://github.com/cloudfoundry/cf-java-client/issues/605.

**Comment by sabbyanandan** [comment]
This has been addressed via https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/pull/120.
