### ISSUE TITLE
Server is not responsive and returning errorsafter some time running

### ISSUE THREAD

**Issue by jaimegag** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#257]
SCDF for PCF v0.1.0-build.81 (Server version 1.1 )
Shell version 1.1.2.RELEASE
Tested on PCF v1.8.19-build.1
App starters loaded from Server Dashboard:  /dashboard/index.html#/apps/bulk-import-apps
    "Maven based Stream Applications with RabbitMQ Binder"

After a while (couple of hours and more) the server becomes non responsive to commands like 'stream list'. Taking 5 minutes to respond.
In the logs I see traces like this:
```
2017-01-27T01:43:41.15-0500 [RTR/0]      OUT dataflow-388f1a78-b1d9-4701-9c03-33812f4877b9.cfapps.haas-49.pez.pivotal.io - [27/01/2017:06:43:41.148 +0000] "GET /streams/definitions?size=10000 HTTP/1.1" 401 0 174 "-" "Apache-HttpClient/4.5 (Java/1.8.0_60)" 10.193.52.250:39762 10.193.52.28:60026 x_forwarded_for:"10.68.248.66, 10.193.52.250" x_forwarded_proto:"https" vcap_request_id:8095f122-91a5-4a93-5490-79bcc8b93825 response_time:0.003257256 app_id:66a1658b-dc9d-4d9b-b913-4ec55038c905 app_index:0
2017-01-27T01:47:17.02-0500 [APP/0]      OUT 2017-01-27 06:47:17.019 ERROR 20 --- [io-8080-exec-10] o.s.c.d.s.c.CloudFoundryAppDeployer      : Caught exception while querying for status of dataflow-P0x1DKT-test3-time
2017-01-27T01:47:17.02-0500 [APP/0]      OUT java.lang.IllegalStateException: Timeout on blocking read
2017-01-27T01:47:17.02-0500 [APP/0]      OUT 	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:107) ~[reactor-core-3.0.4.RELEASE.jar!/:3.0.4.RELEASE]
2017-01-27T01:47:17.02-0500 [APP/0]      OUT 	at reactor.core.publisher.Mono.blockMillis(Mono.java:1215) ~[reactor-core-3.0.4.RELEASE.jar!/:3.0.4.RELEASE]
2017-01-27T01:47:17.02-0500 [APP/0]      OUT 	at reactor.core.publisher.Mono.block(Mono.java:1193) ~[reactor-core-3.0.4.RELEASE.jar!/:3.0.4.RELEASE]
2017-01-27T01:47:17.02-0500 [APP/0]      OUT 	at org.springframework.cloud.deployer.spi.cloudfoundry.CloudFoundryAppDeployer.status(CloudFoundryAppDeployer.java:116) ~[spring-cloud-deployer-cloudfoundry-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
2017-01-27T01:47:17.02-0500 [APP/0]      OUT 	at org.springframework.cloud.dataflow.server.controller.StreamDefinitionController.calculateStreamState(StreamDefinitionController.java:294) [spring-cloud-dataflow-server-core-1.1.2.RELEASE.jar!/:1.1.2.RELEASE]
2017-01-27T01:47:17.02-0500 [APP/0]      OUT 	at org.springframework.cloud.dataflow.server.controller.StreamDefinitionController.access$000(StreamDefinitionController.java:75) [spring-cloud-dataflow-server-core-1.1.2.RELEASE.jar!/:1.1.2.RELEASE]
2017-01-27T01:47:17.02-0500 [APP/0]      OUT 	at org.springframework.cloud.dataflow.server.controller.StreamDefinitionController$Assembler.instantiateResource(StreamDefinitionController.java:363) [spring-cloud-dataflow-server-core-1.1.2.RELEASE.jar!/:1.1.2.RELEASE]
2017-01-27T01:47:17.02-0500 [APP/0]      OUT 	at org.springframework.cloud.dataflow.server.controller.StreamDefinitionController$Assembler.instantiateResource(StreamDefinitionController.java:349) [spring-cloud-dataflow-server-core-1.1.2.RELEASE.jar!/:1.1.2.RELEASE]
2017-01-27T01:47:17.02-0500 [APP/0]      OUT 	at org.springframework.hateoas.mvc.ResourceAssemblerSupport.createResourceWithId(ResourceAssemblerSupport.java:89) [spring-hateoas-0.20.0.RELEASE.jar!/:na]
2017-01-27T01:47:17.02-0500 [APP/0]      OUT 	at org.springframework.hateoas.mvc.ResourceAssemblerSupport.createResourceWithId(ResourceAssemblerSupport.java:81) [spring-hateoas-0.20.0.RELEASE.jar!/:na]
2017-01-27T01:47:17.02-0500 [APP/0]      OUT 	at org.springframework.cloud.dataflow.server.controller.StreamDefinitionController$Assembler.toResource(StreamDefinitionController.java:357) [spring-cloud-dataflow-server-core-1.1.2.RELEASE.jar!/:1.1.2.RELEASE]
2017-01-27T01:47:17.02-0500 [APP/0]      OUT 	at org.springframework.cloud.dataflow.server.controller.StreamDefinitionController$Assembler.toResource(StreamDefinitionController.java:349) [spring-cloud-dataflow-server-core-1.1.2.RELEASE.jar!/:1.1.2.RELEASE]
2017-01-27T01:47:17.02-0500 [APP/0]      OUT 	at org.springframework.data.web.PagedResourcesAssembler.createResource(PagedResourcesAssembler.java:200) [spring-data-commons-1.12.3.RELEASE.jar!/:na]
2017-01-27T01:47:17.02-0500 [APP/0]      OUT 	at org.springframework.data.web.PagedResourcesAssembler.toResource(PagedResourcesAssembler.java:115) [spring-data-commons-1.12.3.RELEASE.jar!/:na]
2017-01-27T01:47:17.02-0500 [APP/0]      OUT 	at org.springframework.cloud.dataflow.server.controller.StreamDefinitionController.list(StreamDefinitionController.java:154) [spring-cloud-dataflow-server-core-1.1.2.RELEASE.jar!/:1.1.2.RELEASE]
```

Trying again will respond faster to  'stream list' but with some streams in an error state.
When trying to undeploy the affected stream I get this Auth error:
```
2017-01-27T01:59:26.04-0500 [RTR/0]      OUT dataflow-388f1a78-b1d9-4701-9c03-33812f4877b9.cfapps.haas-49.pez.pivotal.io - [27/01/2017:06:59:23.277 +0000] "DELETE /streams/deployments/test3 HTTP/1.1" 200 0 0 "-" "Apache-HttpClient/4.5 (Java/1.8.0_60)" 10.193.52.250:39762 10.193.52.28:60026 x_forwarded_for:"10.68.248.66, 10.193.52.250" x_forwarded_proto:"https" vcap_request_id:a9931270-fe34-4f4f-7b8d-272b2006fd5d response_time:2.763759764 app_id:66a1658b-dc9d-4d9b-b913-4ec55038c905 app_index:0
2017-01-27T01:59:26.04-0500 [APP/0]      OUT 2017-01-27 06:59:26.048 ERROR 20 --- [ctor-http-nio-1] o.s.c.d.s.c.CloudFoundryAppDeployer      : Failed to undeploy app dataflow-P0x1DKT-test3-log
2017-01-27T01:59:26.04-0500 [APP/0]      OUT org.cloudfoundry.client.v2.ClientV2Exception: CF-InvalidAuthToken(1000): Invalid Auth Token
```

Commands like 'app list' continue working fine.

**Comment by sabbyanandan** [comment]
This is addressed via: https://github.com/cloudfoundry/cf-java-client/pull/576.
