### ISSUE TITLE
issue with maven

### ISSUE THREAD

**Issue by BLaurent** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#333]
Hi,
I am running version  1.2.0.RELEASE in CF
But when I create stream I have this error:

> Error Deploying Stream. failed to resolve MavenResource: org.springframework.cloud.stream.app:log-sink-rabbit:jar:1.2.0.RELEASE. Configured remote repository:

my server is deployed and env contains : 

>     SPRING_APPLICATION_JSON: { "maven": { "local-repository": null, "remote-repositories": { "repo1": { "url": "http://repo.spring.io/release/" } } } }

What is the error?

Thanks in advance
Regards

**Comment by sabbyanandan** [comment]
Hi, @BLaurent. Let's start with your environment setup. Are you running this behind a proxy? If so, please check [this section in the docs](http://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/1.2.0.RELEASE/reference/htmlsingle/#_configure_maven_properties) for other configurations that are expected. 

Alternatively, if you have only 1 repo to configure, you can supply it as: `MAVEN_REMOTE_REPOSITORIES_REPO1_URL: https://repo.spring.io/libs-release`.

Also, it'd be useful to review the entire `manifest.yml` and as well as more logs.

**Comment by BLaurent** [comment]
Here is my manifest.yml
```
---
applications:
- name: dataflow-server
  memory: 2G
  disk_quota: 2G
  path: target/spring-cloud-dataflow-server-cloudfoundry-0.0.1-SNAPSHOT.jar
  buildpack: https://github.com/cloudfoundry/java-buildpack.git
  services:
    - psql
    - redis
    - uaa
    - logstash
  env:
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_URL: https://api.xxx.io
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_ORG: xxx
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SPACE: xxx
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN: xxxxyyy.io
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_SERVICES: rabbit
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_USERNAME: qbcd@efg.com
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_PASSWORD: 123456
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION: false
    SPRING_APPLICATION_JSON: { "maven": { "local-repository": null, "remote-repositories": { "repo1": { "url": "http://repo.spring.io/release/" } } } }
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_MEMORY: 512
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_DISK: 512
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_INSTANCES: 1
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_BUILDPACK: https://github.com/cloudfoundry/java-buildpack.git
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_ENABLE_RANDOM_APP_NAME_PREFIX: false
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_SERVICES: psql
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_MEMORY: 512
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_DISK: 512
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_INSTANCES: 1
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_BUILDPACK: https://github.com/cloudfoundry/java-buildpack.git
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_ENABLE_RANDOM_APP_NAME_PREFIX: false
    TRUST_CERTS: "api.xxx.io"
```
and some logs 
```
2017-05-26T14:34:16.22+0200 [App/0] OUT [http-nio-62455-exec-7] ERROR o.s.c.d.s.c.RestControllerAdvice - Caught exception while handling a request
2017-05-26T14:34:16.22+0200 [App/0] OUT 	at org.springframework.cloud.deployer.resource.support.DelegatingResourceLoader.getResource(DelegatingResourceLoader.java:140)
2017-05-26T14:34:16.22+0200 [App/0] OUT 	at org.springframework.cloud.dataflow.server.cloudfoundry.resource.LRUCleaningResourceLoader.getResource(LRUCleaningResourceLoader.java:75)
2017-05-26T14:34:16.22+0200 [App/0] OUT org.springframework.cloud.deployer.resource.support.ResourceNotResolvedException: failed to resolve MavenResource: org.springframework.cloud.stream.app:log-sink-rabbit:jar:1.2.0.RELEASE. Configured remote repository:
2017-05-26T14:34:16.22+0200 [App/0] OUT 	at org.springframework.cloud.dataflow.registry.AppRegistration.getResource(AppRegistration.java:132)
2017-05-26T14:34:16.22+0200 [App/0] OUT 	at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.deployStream(StreamDeploymentController.java:273)
2017-05-26T14:34:16.22+0200 [App/0] OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2017-05-26T14:34:16.22+0200 [App/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2017-05-26T14:34:16.22+0200 [App/0] OUT 	at java.lang.reflect.Method.invoke(Method.java:498)
2017-05-26T14:34:16.22+0200 [App/0] OUT 	at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.deploy(StreamDeploymentController.java:201)
2017-05-26T14:34:16.22+0200 [App/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2017-05-26T14:34:16.22+0200 [App/0] OUT 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
2017-05-26T14:34:16.22+0200 [App/0] OUT 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
2017-05-26T14:34:16.22+0200 [App/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
2017-05-26T14:34:16.22+0200 [App/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
2017-05-26T14:34:16.22+0200 [App/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
2017-05-26T14:34:16.22+0200 [App/0] OUT 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
2017-05-26T14:34:16.22+0200 [App/0] OUT 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
2017-05-26T14:34:16.22+0200 [App/0] OUT 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
2017-05-26T14:34:16.22+0200 [App/0] OUT 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
2017-05-26T14:34:16.22+0200 [App/0] OUT 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
2017-05-26T14:34:16.22+0200 [RTR/2] OUT dataflow-server.xxxx.io - [26/05/2017:12:34:16.211 +0000] "POST /streams/deployments/STREAM_3 HTTP/1.1" 500 0 202 "https://dataflow-server.xxxx.io/dashboard/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" 10.72.1.19:46417 x_forwarded_for:"-" x_forwarded_proto:"http" vcap_request_id:210d3e47-1686-4080-4dcd-362df506f8e3 response_time:0.015648547 app_id:93758be4-821f-40ad-8ff5-2f7b674bda5c app_index:- x_b3_spanid:"6659aaf115c43e10" x_b3_traceid:"772e519e1015c749"
```

**Comment by ilayaperumalg** [comment]
@BLaurent I have just tried this version with:

```
SPRING_APPLICATION_JSON: '{ "maven": { "local-repository": null, "remote-repositories": { "repo1": { "url": "http://repo.spring.io/release/" } } } }'
```
and it worked fine.

Given the empty value in the `log` for remote-repositories, do you see this property is set to empty somewhere else? Please check your app environment variable as well.

**Comment by sabbyanandan** [comment]
@BLaurent: One other thing I'd like to point out is that the env-var in your manifest.yml is missing `' '`. It should be:

> SPRING_APPLICATION_JSON: '{ "maven": { "local-repository": null, "remote-repositories": { "repo1": { "url": "http://repo.spring.io/release/" } } } }'

If you don't supply it in this format, the java-buildpack converts it as plain Map and it won't be interpretable by Spring Boot. That's why we see `Configured remote repository:` coming out as empty.

**Comment by BLaurent** [comment]
This seems to fixed everything indeed, related to deploy 
Thanks 
Best Regards
