### ISSUE TITLE
Source Application not being deployed during stream create+deploy

### ISSUE THREAD

**Issue by rahulvijay24feb** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#336]
Hi,
I am trying to deploy a stream with custom Source | log sink through a data server on PCF . The sink application is successfully deployed but source does not get deployed. Inspecting the logs on Data server , I see the below exception :
2017-05-25T23:40:10.737-04:00 [APP/PROC/WEB/0] [OUT] 2017-05-26 03:40:10.737 INFO 17 --- [nio-8080-exec-2] o.s.c.d.s.c.CloudFoundryAppDeployer : Starting deployment of 'dataflow-springier-hindgut-druglog-dataingestorxls'
2017-05-25T23:40:10.737-04:00 [APP/PROC/WEB/0] [OUT] 2017-05-26 03:40:10.737 INFO 17 --- [tcp-client-io-2] o.s.c.d.s.c.CloudFoundryAppDeployer : Successfully computed status [unknown] for dataflow-springier-hindgut-druglog-dataingestorxls
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] 2017-05-26 03:40:10.743 ERROR 17 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler processing failed; nested exception is java.util.zip.ZipError: zip END header not found] with root cause
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:130) ~[zipfs.jar:1.8.0_121]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:139) ~[zipfs.jar:1.8.0_121]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.cloudfoundry.util.FileUtils.normalize(FileUtils.java:80) ~[cloudfoundry-util-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.cloudfoundry.util.FileUtils.toInputStream(FileUtils.java:94) ~[cloudfoundry-util-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.MonoThenApply$MonoThenApplyManager.onNext(MonoThenApply.java:97) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at com.sun.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1021) ~[zipfs.jar:1.8.0_121]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at com.sun.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1030) ~[zipfs.jar:1.8.0_121]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.cloudfoundry.util.tuple.TupleUtils.lambda$function$8(TupleUtils.java:69) ~[cloudfoundry-util-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] java.util.zip.ZipError: zip END header not found
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at com.sun.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1605) ~[zipfs.jar:1.8.0_121]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at java.nio.file.FileSystems.newFileSystem(FileSystems.java:390) ~[na:1.8.0_121]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.SuppressFuseableSubscriber.onNext(FluxFlatMap.java:1324) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.cloudfoundry.util.FileUtils.toInputStream(FileUtils.java:106) ~[cloudfoundry-util-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:892) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.cloudfoundry.operations.applications.DefaultApplications.lambda$push$24(DefaultApplications.java:308) ~[cloudfoundry-operations-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.MonoWhen$MonoWhenSubscriber.onNext(MonoWhen.java:246) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.MonoWhen$MonoWhenCoordinator.signal(MonoWhen.java:202) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.MonoWhen.subscribe(MonoWhen.java:92) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.MonoWhen$MonoWhenCoordinator.subscribe(MonoWhen.java:126) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.MonoWhen$MonoWhenSubscriber.onSubscribe(MonoWhen.java:236) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1508) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:198) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.MonoThenApply.subscribe(MonoThenApply.java:50) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.MonoThenApply.subscribe(MonoThenApply.java:57) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.MonoThenSupply.subscribe(MonoThenSupply.java:54) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.MonoThenSupply$MonoConcatIgnoreManager.drain(MonoThenSupply.java:166) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:80) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.Mono.subscribe(Mono.java:2332) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.MonoProcessor.connect(MonoProcessor.java:437) ~[reactor-core-3.0.2.RELEASE.jar!/:na]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.deploy(StreamDeploymentController.java:186) ~[spring-cloud-dataflow-server-core-1.1.0.M1.jar!/:1.1.0.M1]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.deployer.spi.cloudfoundry.CloudFoundryAppDeployer.deploy(CloudFoundryAppDeployer.java:106) ~[spring-cloud-deployer-cloudfoundry-1.1.0.M1.jar!/:1.1.0.M1]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.deployStream(StreamDeploymentController.java:250) ~[spring-cloud-dataflow-server-core-1.1.0.M1.jar!/:1.1.0.M1]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) ~[spring-webmvc-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.dataflow.server.controller.StreamDefinitionController.save(StreamDefinitionController.java:177) ~[spring-cloud-dataflow-server-core-1.1.0.M1.jar!/:1.1.0.M1]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:832) ~[spring-webmvc-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:743) ~[spring-webmvc-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961) ~[spring-webmvc-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895) ~[spring-webmvc-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967) ~[spring-webmvc-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:869) ~[spring-webmvc-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843) ~[spring-webmvc-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at javax.servlet.http.HttpServlet.service(HttpServlet.java:648) ~[tomcat-embed-core-8.0.36.jar!/:8.0.36]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[tomcat-embed-core-8.0.36.jar!/:8.0.36]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.0.36.jar!/:8.0.36]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) ~[tomcat-embed-core-8.0.36.jar!/:8.0.36]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.36.jar!/:8.0.36]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[tomcat-embed-core-8.0.36.jar!/:8.0.36]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:281) ~[spring-boot-actuator-1.3.7.RELEASE.jar!/:1.3.7.RELEASE]
2017-05-25T23:40:10.744-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.36.jar!/:8.0.36]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:115) ~[spring-boot-actuator-1.3.7.RELEASE.jar!/:1.3.7.RELEASE]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[tomcat-embed-core-8.0.36.jar!/:8.0.36]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346) ~[spring-web-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:207) ~[spring-security-web-4.0.4.RELEASE.jar!/:4.0.4.RELEASE]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176) ~[spring-security-web-4.0.4.RELEASE.jar!/:4.0.4.RELEASE]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262) ~[spring-web-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) ~[spring-web-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121) ~[spring-web-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103) ~[spring-boot-actuator-1.3.7.RELEASE.jar!/:1.3.7.RELEASE]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.36.jar!/:8.0.36]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87) ~[spring-web-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) ~[tomcat-embed-core-8.0.36.jar!/:8.0.36]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-8.0.36.jar!/:8.0.36]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676) [tomcat-embed-core-8.0.36.jar!/:8.0.36]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.36.jar!/:8.0.36]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528) [tomcat-embed-core-8.0.36.jar!/:8.0.36]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [tomcat-embed-core-8.0.36.jar!/:8.0.36]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.36.jar!/:8.0.36]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099) [tomcat-embed-core-8.0.36.jar!/:8.0.36]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520) [tomcat-embed-core-8.0.36.jar!/:8.0.36]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.36.jar!/:8.0.36]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670) [tomcat-embed-core-8.0.36.jar!/:8.0.36]
2017-05-25T23:40:10.745-04:00 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476) [tomcat-embed-core-8.0.36.jar!/:8.0.36]

**Comment by rahulvijay24feb** [comment]
Recreating the jar did the job. Closing this issue
