### ISSUE TITLE
Trying to set up Admin Server using Azure Marketplace MySQL

### ISSUE THREAD

**Issue by lshannon** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#392]
When the application tries to start up for the first time, I get the error below.
Spring Cloud Data Flow Version: 1.30
Azure MySQL: https://azure.microsoft.com/en-us/services/mysql/
Note: This is running on PCF on Azure and the MySQL service is being procured using the Azure Service Broker:
https://docs.pivotal.io/partners/azure-sb/index.html

Seems like something is not correct with the metadata obtained from the service instance, perhaps something to do with Azure and its connection policies around MySQL?

Error:
2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app/:na]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app/:na]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [app/:na]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [app/:na]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLInvalidAuthorizationSpecException: Could not connect: The server name you tried cannot be found. Please use the correct name and retry. Please check your server name u96a56189ce9.
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80) ~[spring-jdbc-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:326) ~[spring-jdbc-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	... 69 common frames omitted
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT Caused by: java.sql.SQLInvalidAuthorizationSpecException: Could not connect: The server name you tried cannot be found. Please use the correct name and retry. Please check your server name u96a56189ce9.
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:135) ~[mariadb-java-client-1.5.9.jar!/:na]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101) ~[mariadb-java-client-1.5.9.jar!/:na]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:91) ~[mariadb-java-client-1.5.9.jar!/:na]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.mariadb.jdbc.Driver.connect(Driver.java:109) ~[mariadb-java-client-1.5.9.jar!/:na]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:310) ~[tomcat-jdbc-8.5.23.jar!/:na]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:203) ~[tomcat-jdbc-8.5.23.jar!/:na]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:735) ~[tomcat-jdbc-8.5.23.jar!/:na]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:667) ~[tomcat-jdbc-8.5.23.jar!/:na]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:198) ~[tomcat-jdbc-8.5.23.jar!/:na]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:131) ~[tomcat-jdbc-8.5.23.jar!/:na]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111) ~[spring-jdbc-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77) ~[spring-jdbc-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	... 70 common frames omitted
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: The server name you tried cannot be found. Please use the correct name and retry. Please check your server name u96a56189ce9.
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:571) ~[mariadb-java-client-1.5.9.jar!/:na]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:503) ~[mariadb-java-client-1.5.9.jar!/:na]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:382) ~[mariadb-java-client-1.5.9.jar!/:na]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:839) ~[mariadb-java-client-1.5.9.jar!/:na]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:479) ~[mariadb-java-client-1.5.9.jar!/:na]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	at org.mariadb.jdbc.Driver.connect(Driver.java:104) ~[mariadb-java-client-1.5.9.jar!/:na]
   2018-03-08T11:17:20.80-0500 [APP/PROC/WEB/0] OUT 	... 78 common frames omitted
   2018-03-08T11:17:20.93-0500 [APP/PROC/WEB/0] OUT 2018-03-08 16:17:20.938  INFO 14 --- [           main] j.LocalContainerEntityManagerFactoryBean : Building JPA container EntityManagerFactory for persistence unit 'default'
   2018-03-08T11:17:20.97-0500 [APP/PROC/WEB/0] OUT 2018-03-08 16:17:20.976  INFO 14 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
   2018-03-08T11:17:20.97-0500 [APP/PROC/WEB/0] OUT 	name: default
   2018-03-08T11:17:20.97-0500 [APP/PROC/WEB/0] OUT 	...]
   2018-03-08T11:17:21.17-0500 [APP/PROC/WEB/0] OUT 2018-03-08 16:17:21.178  INFO 14 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {5.2.12.Final}
   2018-03-08T11:17:21.18-0500 [APP/PROC/WEB/0] OUT 2018-03-08 16:17:21.182  INFO 14 --- [           main] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
   2018-03-08T11:17:21.29-0500 [APP/PROC/WEB/0] OUT 2018-03-08 16:17:21.298  INFO 14 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
   2018-03-08T11:17:21.65-0500 [APP/PROC/WEB/0] OUT 2018-03-08 16:17:21.652  WARN 14 --- [           main] o.h.e.j.e.i.JdbcEnvironmentInitiator     : HHH000342: Could not obtain connection to query metadata : Could not connect: The server name you tried cannot be found. Please use the correct name and retry. Please check your server name u96a56189ce9.
   2018-03-08T11:17:21.65-0500 [APP/PROC/WEB/0] OUT 2018-03-08 16:17:21.657  WARN 14 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
   2018-03-08T11:17:21.65-0500 [APP/PROC/WEB/0] OUT 2018-03-08 16:17:21.659  INFO 14 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 2018-03-08 16:17:21.698 ERROR 14 --- [           main] o.s.boot.SpringApplication               : Application startup failed
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1080) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.cloudfoundry.CloudFoundryDataFlowServer.main(CloudFoundryDataFlowServer.java:33) [classes/:na]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app/:na]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app/:na]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [app/:na]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [app/:na]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT Caused by: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:271) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:233) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:210) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:51) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:94) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:242) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:210) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.handleTypes(MetadataBuildingProcess.java:352) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:111) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:858) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:885) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60) ~[spring-orm-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:360) ~[spring-orm-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:382) ~[spring-orm-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:371) ~[spring-orm-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:336) ~[spring-orm-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	... 24 common frames omitted
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:100) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:54) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:137) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:88) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:259) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
   2018-03-08T11:17:21.69-0500 [APP/PROC/WEB/0] OUT 	... 41 common frames omitted
   2018-03-08T11:18:04.04-0500 [CELL/0] ERR Failed to make TCP connection to port 8080: connection refused
   2018-03-08T11:18:04.43-0500 [API/0] OUT Process has crashed with type: "web"
   2018-03-08T11:18:04.44-0500 [API/0] OUT App instance exited with guid deabac43-dea3-4340-abd8-9142b67214bd payload: {"instance"=>"7053427e-797c-4d61-466a-7b70", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"Instance never healthy after 1m0s: Failed to make TCP connection to port 8080: connection refused", "crash_count"=>4, "crash_timestamp"=>1520525884387281113, "version"=>"3ce7f360-aa41-4899-bb41-1b7c5fa406a9"}

**Comment by scottfrederick** [comment]
I've done some testing of Spring apps using Spring Cloud Connectors or Spring Boot `sql.datasource` configuration to verify similar issues reported on other applications. 

The SDCF server is using the ` org.mariadb.jdbc:mariadb-java-client` JDBC driver for MySQL connections. I've had problems getting that JDBC driver to work with an Azure MySQL service in my testing. 

The `mysql:mysql-connector-java` JDBC driver seems to work fine with Azure MySQL. If using Hibernate auto DDL creation, you might need to also force the MySQL dialect to `org.hibernate.dialect.MySQL55Dialect` instead of the default `org.hibernate.dialect.MySQL5Dialect` (that is, 5.5 dialect instead of 5.0).

**Comment by scottfrederick** [comment]
After further testing, the need to specify the Hibernate dialect depends on the version of Hibernate being used. 

Boot 1.5.x has a managed dependency on Hibernate 5.0.x. With this version of Hibernate, the default `org.hibernate.dialect.MySQL5Dialect` can be used to successfully initialize the database schema at startup. 

Boot 2.0.x has a managed dependency on Hibernate 5.2.x. With this version of Hibernate, the default `MySQL5Dialect` will give errors when initializing the schema with several tested MySQL servers. Forcing the dialect to `MySQL55Dialect` is required with this version of Hibernate.

**Comment by lshannon** [comment]
Thanks Scott! Will try changing the dialect
