### ISSUE TITLE
Bulk unregistration causes datasource connection errors

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#444]
As a user, I'm attempting to bulk unregister Apps from the Dashboard, and I run into the following datasource connection errors. This occurs on default connection config settings.

```
   2018-09-25T19:18:32.94-0700 [APP/PROC/WEB/0] OUT Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
   2018-09-25T19:18:32.94-0700 [APP/PROC/WEB/0] OUT 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676) ~[HikariCP-3.1.0.jar!/:na]
   2018-09-25T19:18:32.94-0700 [APP/PROC/WEB/0] OUT 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190) ~[HikariCP-3.1.0.jar!/:na]
   2018-09-25T19:18:32.94-0700 [APP/PROC/WEB/0] OUT 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155) ~[HikariCP-3.1.0.jar!/:na]
   2018-09-25T19:18:32.94-0700 [APP/PROC/WEB/0] OUT 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[HikariCP-3.1.0.jar!/:na]
   2018-09-25T19:18:32.94-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111) ~[spring-jdbc-4.3.18.RELEASE.jar!/:4.3.18.RELEASE]
   2018-09-25T19:18:32.94-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77) ~[spring-jdbc-4.3.18.RELEASE.jar!/:4.3.18.RELEASE]
```

(notes: SCDF on PCF 1.7 BS w/ Skipper 1.10.0 BS)

**Comment by sabbyanandan** [comment]
This is a user error. Bumping the connection pool setting from what is available as the default, solves the problem.
