### ISSUE TITLE
Cert errors when using the Scheduler v1.2.3 on PAS v2.3

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#450]
As a user, while scheduling for tasks from the Dashboard, I see the following cert errors.

```
   2018-11-06T14:21:27.28-0800 [RTR/0] OUT sabby-test-dataflow-server.apps.navy.springapps.io - [2018-11-06T22:21:27.269+0000] "GET /tasks/definitions/test HTTP/1.1" 200 0 541 "http://sabby-test-dataflow-server.apps.navy.springapps.io/dashboard/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36" "10.194.48.126:58462" "10.194.48.32:61046" x_forwarded_for:"10.64.249.138, 10.194.48.126" x_forwarded_proto:"http" vcap_request_id:"b6bec174-9d1a-4c39-7cca-a9a5be078565" response_time:0.010864859 app_id:"11f1d600-997a-4739-b5e6-c63828819632" app_index:"0" x_b3_traceid:"16952e4454e0ae2c" x_b3_spanid:"16952e4454e0ae2c" x_b3_parentspanid:"-"
   2018-11-06T14:21:27.28-0800 [RTR/0] OUT 
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 2018-11-06 22:21:27.456 ERROR 37 --- [ry-client-nio-1] r.ipc.netty.channel.ContextHandler       : Error cannot be forwarded to user-facing Mono
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT javax.net.ssl.SSLHandshakeException: General SSLEngine problem
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1529) ~[na:1.8.0_181]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535) ~[na:1.8.0_181]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813) ~[na:1.8.0_181]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[na:1.8.0_181]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[na:1.8.0_181]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:294) ~[netty-handler-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1275) [netty-handler-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1177) [netty-handler-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1221) [netty-handler-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [netty-codec-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [netty-codec-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [netty-codec-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-common-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_181]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728) ~[na:1.8.0_181]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:330) ~[na:1.8.0_181]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322) ~[na:1.8.0_181]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614) ~[na:1.8.0_181]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[na:1.8.0_181]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052) ~[na:1.8.0_181]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at sun.security.ssl.Handshaker$1.run(Handshaker.java:992) ~[na:1.8.0_181]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at sun.security.ssl.Handshaker$1.run(Handshaker.java:989) ~[na:1.8.0_181]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_181]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1467) ~[na:1.8.0_181]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1435) [netty-handler-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1343) [netty-handler-4.1.25.Final.jar!/:4.1.25.Final]
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT 	... 19 common frames omitted
   2018-11-06T14:21:27.45-0800 [APP/PROC/WEB/0] OUT Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
```

To reproduce, open the Dashboard, go to the `Schedules` tab, you will see "[Object] object" alert in the GUI. The server logs should include the cert errors.

Notes:
- Stack: SCDF 1.7.1 BS + Skipper 1.1.1 BS.
- In this PAS environment, SCDF is configured to skip SSL via `SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION: true`.

**Comment by sabbyanandan** [comment]
When using the Scheduler CLI (with skip ssl set to true), I'm able to create and schedule for jobs.

```
 cf schedule-job AAAA1-schedule "*/4 * ? * *"                                                                                                                                                                                                                                                                                                                  ⏎
Scheduling job AAAA1-schedule for test to execute based on expression */4 * ? * * in org sanandan / space sanandan-space as admin
OK

 cf jobs                                                                                                                                                                                                                                                                                                                                                       ⏎
Listing jobs for org sanandan / space sanandan-space as admin
Job Name         App Name   Command
AAAA1-schedule   test       JAVA_OPTS="-agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.12.0_RELEASE=printHeapHistogram=1 -Djava.io.tmpdir=$TMPDIR -Djava.ext.dirs=$PWD/.java-buildpack/container_security_provider:$PWD/.java-buildpack/open_jdk_jre/lib/ext -Djava.security.properties=$PWD/.java-buildpack/java_security/java.security $JAVA_OPTS" && CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.10.0_RELEASE -totMemory=$MEMORY_LIMIT -stackThreads=300 -loadedClasses=15375 -poolType=metaspace -vmOptions="$JAVA_OPTS") && echo JVM Memory Configuration: $CALCULATED_MEMORY && JAVA_OPTS="$JAVA_OPTS $CALCULATED_MEMORY" && SERVER_PORT=$PORT eval exec $PWD/.java-buildpack/open_jdk_jre/bin/java $JAVA_OPTS -cp $PWD/. org.springframework.boot.loader.JarLauncher
OK

➜ ~/Downloads
 cf job-schedules
Getting scheduled jobs for org sanandan / space sanandan-space as admin

App Name: test
AAAA1-schedule   JAVA_OPTS="-agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.12.0_RELEASE=printHeapHistogram=1 -Djava.io.tmpdir=$TMPDIR -Djava.ext.dirs=$PWD/.java-buildpack/container_security_provider:$PWD/.java-buildpack/open_jdk_jre/lib/ext -Djava.security.properties=$PWD/.java-buildpack/java_security/java.security $JAVA_OPTS" && CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.10.0_RELEASE -totMemory=$MEMORY_LIMIT -stackThreads=300 -loadedClasses=15375 -poolType=metaspace -vmOptions="$JAVA_OPTS") && echo JVM Memory Configuration: $CALCULATED_MEMORY && JAVA_OPTS="$JAVA_OPTS $CALCULATED_MEMORY" && SERVER_PORT=$PORT eval exec $PWD/.java-buildpack/open_jdk_jre/bin/java $JAVA_OPTS -cp $PWD/. org.springframework.boot.loader.JarLauncher
                 22c21ee4-3222-4f0a-8875-317cadb3c69d                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */4 * ? * *
OK
```

**Comment by sabbyanandan** [comment]
Turns out I've had the Scheduler URL mapped to a different environment; hence the reason for the SSL handshake errors. 😩

With that mapped correctly, everything works as expected.
