### ISSUE TITLE
TAP'ing Twitterstream causes Server CPU to spike >100%

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#93]
As a user, I deployed a stream and TAP'd the primary pipeline to perform downstream analytics; however, I see the server's CPU cycling >100%. 

**streams:**
```
(1) dataflow:>stream create tweets --definition "twitterstream --consumerKey=<CONSUMER_KEY> --consumerSecret=<CONSUMER_SECRET> --accessToken=<ACCESS_TOKEN> --accessTokenSecret=<ACCESS_TOKEN_SECRET> | log"
Created new stream 'tweets'

(2) dataflow:>stream create tweetlang  --definition ":tweets.twitterstream > field-value-counter --fieldName=lang --name=language --store=redis" --deploy
Created and deployed new stream 'tweetlang'

(3) dataflow:>stream create tagcount --definition ":tweets.twitterstream > field-value-counter --fieldName=entities.hashtags.text --name=hashtags --store=redis" --deploy
Created and deployed new stream 'tagcount'

(4) dataflow:>stream deploy tweets
Deployed stream 'tweets'
```

**metrics when apps were running**
![image](https://cloud.githubusercontent.com/assets/1562654/15130388/e1a330f0-15fc-11e6-9dec-4978407b2d2a.png)

**metrics when apps were shutdown:**
![image](https://cloud.githubusercontent.com/assets/1562654/15130426/2625e0ec-15fd-11e6-855f-36422917cc77.png)

**memory at peak results in OOM:**
```
3b-9dec-adf5e661e6ab
2016-05-09T15:20:05.78-0700 [APP/0]      OUT Exit status 255
2016-05-09T15:20:05.78-0700 [CELL/0]     OUT Exit status 255
2016-05-09T15:20:05.80-0700 [API/0]      OUT App instance exited with guid b08abbc4-deae-4a3b-9dec-adf5e661e6ab payload: {"instance"=>"761b329d-01b7-4635-4790-324fac3717e7", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 2 error(s) occurred:\n\n* Exited with status 255 (out of memory)\n* Exited with status 255 (out of memory)\n* cancelled", "crash_count"=>1, "crash_timestamp"=>1462832405786779355, "version"=>"c7bfd3e8-36be-4601-b3e6-1fa77b84287c"}
```

**Comment by sabbyanandan** [comment]
Tried simple TAPs on `ticktock` stream; though the CPU/memory spiked when the streams app bootstrapped, but it eventually goes down.

**streams:**
```
dataflow:>stream list
╔════════════════════════╤═════════════════════════════════╤════════╗
║      Stream Name       │        Stream Definition        │ Status ║
╠════════════════════════╪═════════════════════════════════╪════════╣
║peak-cpu-test-first-tap │:peak-cpu-test-primary.time > log│deployed║
║peak-cpu-test-second-tap│:peak-cpu-test-primary.time > log│deployed║
║peak-cpu-test-primary   │time | log                       │deployed║
╚════════════════════════╧═════════════════════════════════╧════════╝
```

**metrics:**
![image](https://cloud.githubusercontent.com/assets/1562654/15130537/0da982b6-15fe-11e6-9981-5ad84f1e2596.png)

This narrows it down to analytic-store's persistence layer in the server, which was used by the counters in the original streams. This still doesn't correlate to the memory consumption, though. It is still >80% even after all the streams are destroyed.

**Comment by markpollack** [comment]
What environment are you using for this?

**Comment by ilayaperumalg** [comment]
I have run some tests locally (as I couldn't get to look at PCF metrics working yet) and don't seem to get any issues with CPU/memory even with reasonably high volume of data (at least to match the above set of streams). By the way, if you can reproduce this again, does setting redis connection pool properties help anyway?

**Comment by ilayaperumalg** [comment]
@sabbyanandan Tried this in multiple CF environments and don't seem to find any issues with CPU/memory. There was one occasion where I ran into OOM error but after I cleaned up the environment, I couldn't replicate that.
If you run into the same issue again, I would like to see the thread dump of the server process (jstack pid).

**Comment by sabbyanandan** [comment]
OOM error is easily reproducible. @markpollack ran into it yday, too. With default 1G as memory, please try deploying/destroying streams (2 - 3 times).

**Comment by ilayaperumalg** [comment]
The OOM error might be related to  `async` handling of deploy in the CloudFoundry app deployer. When the deploy/undeploy operations are invoked continuously, then the following exception is thrown:

```
2016-05-25T16:12:29.22+0530 [APP/0]      OUT java.lang.IllegalStateException: Application a1-time failed during staging
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at org.cloudfoundry.util.ExceptionUtils.illegalState(ExceptionUtils.java:60) ~[cloudfoundry-util-2.0.0.M4.jar!/:2.0.0.M4]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at org.cloudfoundry.operations.applications.DefaultApplications.waitForStaging(DefaultApplications.java:1353) ~[cloudfoundry-operations-2.0.0.M4.jar!/:2.0.0.M4]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at org.cloudfoundry.operations.applications.DefaultApplications.lambda$startApplicationAndWait$102(DefaultApplications.java:1180) ~[cloudfoundry-operations-2.0.0.M4.jar!/:2.0.0.M4]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:371) ~[reactor-core-2.5.0.M3.jar!/:na]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:125) ~[reactor-core-2.5.0.M3.jar!/:na]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:85) ~[reactor-core-2.5.0.M3.jar!/:na]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at reactor.core.publisher.UnicastProcessor.drain(UnicastProcessor.java:131) ~[reactor-core-2.5.0.M3.jar!/:na]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at reactor.core.publisher.UnicastProcessor.onNext(UnicastProcessor.java:213) ~[reactor-core-2.5.0.M3.jar!/:na]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnPipeline.onNext(FluxSubscribeOn.java:134) ~[reactor-core-2.5.0.M3.jar!/:na]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at reactor.core.subscriber.SignalEmitter.emit(SignalEmitter.java:198) ~[reactor-core-2.5.0.M3.jar!/:na]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at reactor.core.subscriber.SignalEmitter.onNext(SignalEmitter.java:444) ~[reactor-core-2.5.0.M3.jar!/:na]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at org.cloudfoundry.spring.util.AbstractSpringOperations.lambda$null$1(AbstractSpringOperations.java:68) ~[cloudfoundry-client-spring-2.0.0.M4.jar!/:2.0.0.M4]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at reactor.core.publisher.FluxYieldingEmitter$YieldingSignalEmitter.request(FluxYieldingEmitter.java:75) ~[reactor-core-2.5.0.M3.jar!/:na]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at reactor.core.util.DeferredSubscription.set(DeferredSubscription.java:71) ~[reactor-core-2.5.0.M3.jar!/:na]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnPipeline.onSubscribe(FluxSubscribeOn.java:129) ~[reactor-core-2.5.0.M3.jar!/:na]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at reactor.core.subscriber.SignalEmitter.start(SignalEmitter.java:170) ~[reactor-core-2.5.0.M3.jar!/:na]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at reactor.core.publisher.FluxYieldingEmitter.subscribe(FluxYieldingEmitter.java:43) ~[reactor-core-2.5.0.M3.jar!/:na]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:153) ~[reactor-core-2.5.0.M3.jar!/:na]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:170) ~[reactor-core-2.5.0.M3.jar!/:na]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at reactor.core.publisher.FluxSubscribeOn$SourceSubscribeTask.run(FluxSubscribeOn.java:363) ~[reactor-core-2.5.0.M3.jar!/:na]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at reactor.core.publisher.Computations$ProcessorWorker.onNext(Computations.java:919) ~[reactor-core-2.5.0.M3.jar!/:na]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at reactor.core.publisher.Computations$ProcessorWorker.onNext(Computations.java:883) ~[reactor-core-2.5.0.M3.jar!/:na]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at reactor.core.publisher.WorkQueueProcessor$QueueSubscriberLoop.run(WorkQueueProcessor.java:842) ~[reactor-core-2.5.0.M3.jar!/:na]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_71-]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_71-]
2016-05-25T16:12:29.22+0530 [APP/0]      OUT 	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_71-]
```
and subsequently the OOM error occurs.

**Comment by ilayaperumalg** [comment]
I guess we need to track this OOM error on stream deploy/undeploy in a different story as the scope of this issue is not related to deploy/undeploy operations performed continuously. Created https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues/107

**Comment by sabbyanandan** [comment]
Since the CPU issue isn't consistently reproducible, I'll close this. The memory problem is persistent and we have a separate story for that.
