### ISSUE TITLE
Cannot bind service at app level

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#99]
As a user, I'm deploying a stream with service binding at an app level, but I'm unable to successfully run it. This used to be supported in [M2](https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/pull/16); perhaps this was lost while refactoring to `spring-cloud-deployer` SPI.

**stream:**
```
dataflow:>stream create --name foo-mysql --definition "http | jdbc --tableName=names --columns=name"
dataflow:>stream deploy foo-mysql --properties module.jdbc.cloudfoundry.services=mysql
```

(_where: `mysql` is the name of the service running in cf_)

**error:**
```
2016-05-13T15:15:18.85-0700 [APP/0]      ERR Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
2016-05-13T15:15:18.85-0700 [APP/0]      ERR 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
2016-05-13T15:15:18.85-0700 [APP/0]      ERR 	at java.lang.Thread.run(Thread.java:745)
2016-05-13T15:15:18.85-0700 [APP/0]      ERR Caused by: java.lang.reflect.InvocationTargetException
2016-05-13T15:15:18.85-0700 [APP/0]      ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-05-13T15:15:18.85-0700 [APP/0]      ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2016-05-13T15:15:18.85-0700 [APP/0]      ERR 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2016-05-13T15:15:18.85-0700 [APP/0]      ERR 	at java.lang.reflect.Method.invoke(Method.java:497)
2016-05-13T15:15:18.85-0700 [APP/0]      ERR 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
2016-05-13T15:15:18.85-0700 [APP/0]      ERR 	... 1 more
2016-05-13T15:15:18.85-0700 [APP/0]      ERR Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.stream.app.jdbc.sink.JdbcSinkConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jdbcMessageHandler' defined in class org.springframework.cloud.stream.app.jdbc.sink.JdbcSinkConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [javax.sql.DataSource]: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration$NonEmbeddedConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Cannot determine embedded database driver class for database type NONE. If you want an embedded database please put a supported one on the classpath. If you have database settings to be loaded from a particular profile you may need to active it (the profiles "cloud" are currently active).; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration$NonEmbeddedConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Cannot determine embedded database driver class for database type NONE. If you want an embedded database please put a supported one on the classpath. If you have database settings to be loaded from a particular profile you may need to active it (the profiles "cloud" are currently active).
```

**Comment by sobychacko** [comment]
This is the right property to use based on the latest:

`dataflow:>stream deploy foo-mysql --properties module.jdbc.spring.cloud.deployer.cloudfoundry.defaults.services=mysql`

It used to be `module.jdbc.cloudfoundry.service`. @markfisher @markpollack What do you think about going back to this property key?

**Comment by markpollack** [comment]
The fully qualified suffix after `module.jdbc` seems good as it will avoid collisions in the future.  I don't like the use of the word `defaults`, even if it was in yaml vs. property file syntax.  Related to that for k8s and mesos there isn't a `defaults` keyword.  

See https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/master/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesAppDeployer.java#L283

and

https://github.com/spring-cloud/spring-cloud-deployer-mesos/blob/master/src/main/java/org/springframework/cloud/deployer/spi/mesos/marathon/MarathonAppDeployer.java#L175

I didn't check YARN, but I think we should be consistent across the board by having it be fully qualified with the deployer's `@ConfigurationProperties` prefix and remove the use of `default`.

**Comment by sobychacko** [comment]
PR is issued for addressing this. https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/pull/38
